### PR TITLE
109 engagement detail view

### PR DESCRIPTION
**Pull request by bcloutier7**
# Description

Implemented Detail view for Engagements. This is only to show the data.
This has no styling to it... yet.

## Test Instructions

1. Navigate to search engagements and contacts. 
2. select an engagement and it should bring you to the view detail.

## Help Requested

I believe I am using the state properly in engagement/_id. I copied what Jordan had done for contacts.

## Checklist
- [ ] Strings use placeholders for translation (No hard coded strings)
- [ ] Unit tests have been added/updated

### CODE REVIEW

**Comment by bcloutier7** [comment]
Marco noticed that I missed the contacts. Adding them now...

**Comment by bcloutier7** [comment]
There is a bug when selecting a contact within an engagement. I do not know what causes the bug.

**Comment by will0684** [comment]
> There is a bug when selecting a contact within an engagement. I do not know what causes the bug.

I just merged main into your branch. Everything seems to work fine with that. You will want to ensure you are updated to main's most recent code before and during your PR being up. 👍

**Comment by will0684** [comment]
Once you merge main into the branch and push, I'll approve it @bcloutier7

**Comment by bcloutier7** [comment]
Sounds good I am also adding styling to it.

**Pull request merged**
