### PR TITLE
115 engagement edit

### PR DESCRIPTION
**Pull request by will0684**
# Description

[#115 View Engagement: Edit mode](https://taiga.dts-stn.com/project/pond-knowlege-management-portal/us/115?milestone=20)

This PR contains the feature for editing engagements.

# Story Acceptance Criteria

[#115 View Engagement: Edit Mode](https://taiga.dts-stn.com/project/pond-knowlege-management-portal/us/115?milestone=20)

As a policy analyst I want to be able to update Engagement details so that RMP users always have up to date info on Engagements in the system.

Acceptance Criteria:

- User performs Engagement search and clicks a Engagement from the search results, Engagement detail view page is displayed and all Engagement information is displayed
- User clicks "Edit Engagement" button and Engagement detail page changes state to edit mode displaying user inputs to change engagement info, displaying Cancel/Submit buttons
- User updates Engagement fields with valid user input and clicks submit, Engagement form is hidden and Engagement detail page is displayed with updated info and success prompt is displayed(toast message top of page? match strategy with Contact detail view)
- User updates Engagement fields with invalid user input and clicks submit, error prompt is displayed, informing user of form validation errors
- User clicks "Cancel" from the Engagement card:edit mode and returns to Engagement detail view
- Above passes on Web/Mobile
- All Engagement data fields are displayed and can be edited, excluding comments

Exclusions:

- Comments submitted when creating the engagement are not editable

## Test Instructions

1. Go to Engagement detail view
1. Select Edit at the bottom of the page
1. See edit page is populated with the data of the current Engagement
1. Modify fields with valid and invalid values, see validation
1. Save engagement with invalid fields, validation behaviour should occur
1. Save engagement with valid fields, you should be returned to the detail page which should have the modified fields and a success notification should appear at the top of the page
1. If there is an error with the db, user should remain on the page and see a notification for the error

## Checklist
- [x] Strings use placeholders for translation (No hard coded strings)
- [ ] Unit tests have been added/updated

### CODE REVIEW

**Comment by will0684** [comment]
@MarcoGoC great call out thank you, fixing now

**Comment by MarcoGoC** [comment]
not the comnent no. 
however the list of tags was not updated as well

**Comment by will0684** [comment]
> I am getting a 500 error when I select to edit the date of the engagement.
> client.js?06a0:84 TypeError: _vm.engagementDetail.date.split is not a function

Addressed in the last commit

**Comment by MarcoGoC** [comment]
small little thing around the tag sections when in mobile 
other than that all good

**Comment by will0684** [comment]
> small little thing around the tag sections when in mobile
> other than that all good
> div css changes for tags to be vertical when on mobile
> 
> ```
>       <div class="flex-no-wrap md:flex">
>           <eng-tags v-for="(tag, index) in engagementDetail.tags" :key="index">
>             {{ tag }}
>             <button class="delete-btn" @click.prevent="deleteTag(index)">
>               x
>             </button>
>           </eng-tags>
>         </div>
> ```

Tried this but I think I'm missing something, the tags stretch out to fill the space and the X button is all the way on the left with the text.

> small little thing around the tag sections when in mobile
> other than that all good
> div css changes for tags to be vertical when on mobile
> 
> ```
>       <div class="flex-no-wrap md:flex">
>           <eng-tags v-for="(tag, index) in engagementDetail.tags" :key="index">
>             {{ tag }}
>             <button class="delete-btn" @click.prevent="deleteTag(index)">
>               x
>             </button>
>           </eng-tags>
>         </div>
> ```

This is now fixed.

**Pull request merged**
